/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import hospital.management.system.Doctor;
import hospital.management.system.DoctorDirectory;
import hospital.management.system.Encounter;
import hospital.management.system.EncounterHistory;
import hospital.management.system.Patient;
import hospital.management.system.PatientDirectory;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SHREYAS
 */
public class BookAppointment extends javax.swing.JFrame {

    /**
     * Creates new form BookAppointment
     */
    PatientDirectory patientDir;
    DoctorDirectory records;
    EncounterHistory encounterHist;
    private String username;
    String community;
    int doctorID;
    Patient patient = new Patient();
    private TableRowSorter sorter;
    
    public BookAppointment(String username, EncounterHistory encounterHist) {
        initComponents();
        
        if(encounterHist == null){
            this.encounterHist = new EncounterHistory();
        }
        else{
            this.encounterHist = encounterHist;
        }
        
        for(Patient p:patientDir.getPatientDir()){
            if(username.equals(p.getEmailId())){
                patient = p;
                community = p.residence.getCommunityName();
                System.out.println(community);
            }
        }
        

        for(Doctor d:DoctorDirectory.getRecords()){
            if(community.equals(d.residence.getCommunityName())){
                doctorID = d.getDoctorID();
                System.out.println(doctorID);
            }
        }
        populateTableData(doctorID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BADoctorTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BAPatientIDtxt = new javax.swing.JTextField();
        BADoctorIDtxt = new javax.swing.JTextField();
        BAEncounterIDtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BADoctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BADoctorTable);

        jButton1.setText("select doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("book appointment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("patient id");

        jLabel2.setText("doctor id");

        jLabel3.setText("encounter id");

        BAPatientIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAPatientIDtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BAPatientIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BADoctorIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BAEncounterIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BAPatientIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BADoctorIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BAEncounterIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i = BADoctorTable.getSelectedRow();
        if (i<0){
            JOptionPane.showMessageDialog(this, "Please select a doctor to proceed.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) BADoctorTable.getModel();
        Doctor dr = (Doctor) model.getValueAt(i, 1);

      
            int pID = patient.getPatientId();
            int drID = dr.getDoctorID();
            int encID = Integer.parseInt(BAEncounterIDtxt.getText());
            

            Encounter enc = encounterHist.addNewEncounter(encID, , time,  pID,  drID);

            enc.setEncounterID(encID);
            
            enc.setPatientId(pID);
            enc.doctor.setDoctorID(drID);

            JOptionPane.showMessageDialog(this, "Appointment booked successfully");

            BAEncounterIDtxt.setText(null);
            BAPatientIDtxt.setText(null);
            BADoctorIDtxt.setText(null);
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BAPatientIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAPatientIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAPatientIDtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = BADoctorTable.getSelectedRow();

        if (i<0){
            JOptionPane.showMessageDialog(this, "Please select a doctor to proceed.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) BADoctorTable.getModel();
        Doctor dr = (Doctor) model.getValueAt(i, 1);
        Encounter enc = new Encounter();
        
        
        int randomEncId=(int)(Math.random()*999+100);
        
        for(Encounter e:EncounterHistory.getEncounterHist()){
            if(randomEncId==e.getEncounterID()){
               
               randomEncId =(int)(Math.random()*999+100);
            }
        }

        int slots = dr.getSlotsAvailable();
        if(slots > 0){
            int patientId = patient.getPatientId();
            int doctorId = dr.getDoctorID();
            enc.setEncounterID(Integer.parseInt(BAEncounterIDtxt.getText()));
            BAPatientIDtxt.setText(String.valueOf(patientId));
            BADoctorIDtxt.setText(String.valueOf(doctorId));

            BAEncounterIDtxt.setEditable(false);
            BAPatientIDtxt.setEditable(false);
            BADoctorIDtxt.setEditable(false);

        }
        else{
            JOptionPane.showMessageDialog(this, "Selected doctor has 0 slots available. Please select another doctor");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BADoctorIDtxt;
    private javax.swing.JTable BADoctorTable;
    private javax.swing.JTextField BAEncounterIDtxt;
    private javax.swing.JTextField BAPatientIDtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
