/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import hospital.management.system.Doctor;
import hospital.management.system.DoctorDirectory;
import hospital.management.system.Encounter;
import hospital.management.system.EncounterHistory;
import hospital.management.system.Patient;
import hospital.management.system.PatientDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHREYAS
 */
public class DoctorLoggedIn extends javax.swing.JFrame {

    /**
     * Creates new form DoctorLoggedIn
     */
    DoctorDirectory records = new DoctorDirectory();
    EncounterHistory encounterHist = new EncounterHistory();
    PatientDirectory patientDir = new PatientDirectory();
    Doctor doc1;
    public String username;
    public String community;
    
    public DoctorLoggedIn(String username) {
        initComponents();
        this.username = username;
        for(Doctor d: records.getRecords()){
            if(username.equals(d.getEmailId())){
                doc1 = d;
            }
        }
        patientDashboardTable();
    }
    public DoctorLoggedIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        createEncounter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientDashboardTable = new javax.swing.JTable();
        viewPat = new javax.swing.JButton();
        patientSugarLevelLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SugarLevelEnctxt = new javax.swing.JTextField();
        doctorNameEnctxt = new javax.swing.JTextField();
        BloodPresEnctxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        patientBloodPressureLbl = new javax.swing.JLabel();
        patientIDEnctxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BodyTempEnctxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        encounterIDEnctxtr = new javax.swing.JTextField();
        doctorIDEnctxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PatientEncNametxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DiagnosisEnctxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SymptomsEnctxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CreateEnctxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        createEncounter.setText("Schdeule / Update Encounter");
        createEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createEncounter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(createEncounter)
                .addContainerGap(537, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        patientDashboardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Patient ID", "Contact ", "Email ID", "Gender", "Age", "Address", "Blood Grp", "Height", "Weight", "Allergies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientDashboardTable.setAutoscrolls(false);
        jScrollPane2.setViewportView(patientDashboardTable);

        viewPat.setText("View Selected Patient");
        viewPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatActionPerformed(evt);
            }
        });

        patientSugarLevelLbl.setText("Sugar Level");

        jLabel11.setText("Doctor Name");

        SugarLevelEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SugarLevelEnctxtActionPerformed(evt);
            }
        });

        doctorNameEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorNameEnctxtActionPerformed(evt);
            }
        });

        BloodPresEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPresEnctxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Patient ID");

        patientBloodPressureLbl.setText("Blood Pressure");

        patientIDEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDEnctxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Time");

        BodyTempEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyTempEnctxtActionPerformed(evt);
            }
        });

        jLabel9.setText("Body Temperature");

        encounterIDEnctxtr.setEditable(false);

        doctorIDEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorIDEnctxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Date");

        jLabel7.setText("Diagnosis");

        jLabel4.setText("Encounter ID");

        jLabel3.setText("Doctor ID");

        SymptomsEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymptomsEnctxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient Name");

        jLabel6.setText("Symptoms");

        CreateEnctxt.setText("Create");
        CreateEnctxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateEnctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEnctxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(viewPat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(PatientEncNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(patientIDEnctxt)
                                            .addComponent(doctorIDEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(102, 102, 102))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(doctorNameEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(encounterIDEnctxtr, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientBloodPressureLbl)
                                    .addComponent(patientSugarLevelLbl)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BodyTempEnctxt)
                                    .addComponent(SugarLevelEnctxt)
                                    .addComponent(BloodPresEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SymptomsEnctxt, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(DiagnosisEnctxt))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPat)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PatientEncNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientIDEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorIDEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorNameEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(encounterIDEnctxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BloodPresEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientBloodPressureLbl))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SugarLevelEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientSugarLevelLbl))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BodyTempEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SymptomsEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiagnosisEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(CreateEnctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 546, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEncounterActionPerformed
        // TODO add your handling code here:
        int rowindex = patientDashboardTable.getSelectedRow();
        DoctorEncounterRegistration  encounterRegistration=new DoctorEncounterRegistration(encounterHist,doc1.getDoctorID(),doc1.        getEmailId());
        jScrollPane2.setRightComponent(encounterRegistration);
    }//GEN-LAST:event_createEncounterActionPerformed

    private void viewPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatActionPerformed
        // TODO add your handling code here:
        int i = patientDashboardTable.getSelectedRow();

        if (i<0){
            JOptionPane.showMessageDialog(this, "Please select a patient to proceed.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) patientDashboardTable.getModel();
        Patient p = (Patient) model.getValueAt(i, 0);
        int pID = p.getPatientId();
        patientIDEnctxt.setText(String.valueOf(pID));
        PatientEncNametxt.setText(p.getName());

    }//GEN-LAST:event_viewPatActionPerformed

    private void SugarLevelEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SugarLevelEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SugarLevelEnctxtActionPerformed

    private void doctorNameEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorNameEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorNameEnctxtActionPerformed

    private void BloodPresEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPresEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPresEnctxtActionPerformed

    private void patientIDEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDEnctxtActionPerformed

    private void BodyTempEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyTempEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyTempEnctxtActionPerformed

    private void doctorIDEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorIDEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorIDEnctxtActionPerformed

    private void SymptomsEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymptomsEnctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymptomsEnctxtActionPerformed

    private void CreateEnctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEnctxtActionPerformed
        // TODO add your handling code here:
        Encounter enc = new Encounter();
        boolean b1 = patientDir.checkPID(Integer.parseInt(patientIDEnctxt.getText()));
        boolean b2 = records.checkDID(Integer.parseInt(doctorIDEnctxt.getText()));
        if(b1 && b2){
            int randomEncId=(int)(Math.random()*999+100);

            for(Encounter e:EncounterHistory.getEncounterHist()){
                if(randomEncId==e.getEncounterID()){

                    randomEncId =(int)(Math.random()*999+100);
                }
            }

            enc.setEncounterID((int)(Math.random()*999+100));
            enc.patient.setPatientId(Integer.parseInt(patientIDEnctxt.getText()));
            enc.doctor.setDoctorID(Integer.parseInt(doctorIDEnctxt.getText()));
            
            enc.patient.setName(PatientEncNametxt.getText());
            enc.doctor.setName(doctorNameEnctxt.getText());
            enc.setSugarLevel(Float.parseFloat(SugarLevelEnctxt.getText()));
            enc.setBldPressure(Float.parseFloat(BloodPresEnctxt.getText()));
            enc.setBodyTemp(Float.parseFloat(BloodPresEnctxt.getText()));
            enc.setSymptoms(SymptomsEnctxt.getText());
            enc.setEncDiagnosis(DiagnosisEnctxt.getText());

            EncounterHistory.encounterHist.add(enc);
            JOptionPane.showMessageDialog(this, "Encounter Successfully Added");

        }
        else{
            JOptionPane.showMessageDialog(this, "Entered ID doesn't exist");
        }
    }//GEN-LAST:event_CreateEnctxtActionPerformed
    public void patientDashboardTable(){
    
        DefaultTableModel model = (DefaultTableModel) patientDashboardTable.getModel();
        model.setRowCount(0);
        
        System.out.println("Done");
        for(Patient pt:patientDir.getPatientDir()){
            Object[] row=new Object[11];
            row[0]=pt;
            row[1]=pt.getPatientId();
            row[2]=pt.getContactDetails();
            row[3]=pt.getEmailId();
            row[4]=pt.getGender();
            row[5]=pt.getAge();
            row[6]=pt.residence.getHouseNumber() + ", "+ ", " + pt.residence.getCommunityName() + ", " + pt.residence.getCityName() + ", " +             pt.residence.getState()+ "," + pt.residence.getZip();
            row[7]=pt.getBloodgroup();
            row[8]=pt.getPatientheight();
            row[9]=pt.getPatientWeight();
            //row[10]=pt.getAllergies();
            model.addRow(row);
                    
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorLoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorLoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorLoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorLoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorLoggedIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodPresEnctxt;
    private javax.swing.JTextField BodyTempEnctxt;
    private javax.swing.JButton CreateEnctxt;
    private javax.swing.JTextField DiagnosisEnctxt;
    private javax.swing.JTextField PatientEncNametxt;
    private javax.swing.JTextField SugarLevelEnctxt;
    private javax.swing.JTextField SymptomsEnctxt;
    private javax.swing.JButton createEncounter;
    private javax.swing.JTextField doctorIDEnctxt;
    private javax.swing.JTextField doctorNameEnctxt;
    private javax.swing.JTextField encounterIDEnctxtr;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel patientBloodPressureLbl;
    private javax.swing.JTable patientDashboardTable;
    private javax.swing.JTextField patientIDEnctxt;
    private javax.swing.JLabel patientSugarLevelLbl;
    private javax.swing.JButton viewPat;
    // End of variables declaration//GEN-END:variables
}
