/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author SHREYAS
 */
public class mainlogin extends javax.swing.JFrame {

    /**
     * Creates new form mainlogin
     */
    public mainlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeladmin = new javax.swing.JLabel();
        labelsystemadmin = new javax.swing.JLabel();
        labelpatient = new javax.swing.JLabel();
        labeldoctor = new javax.swing.JLabel();
        buttondoctor = new javax.swing.JButton();
        buttonpatient = new javax.swing.JButton();
        buttonsystemadmin = new javax.swing.JButton();
        buttonadmin = new javax.swing.JButton();
        buttoncancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeladmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHREYAS\\OneDrive\\Desktop\\admin.jpg")); // NOI18N
        labeladmin.setText("jLabel2");

        labelsystemadmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHREYAS\\OneDrive\\Desktop\\system admin.jpg")); // NOI18N
        labelsystemadmin.setText("jLabel2");

        labelpatient.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHREYAS\\OneDrive\\Desktop\\patient.jpg")); // NOI18N
        labelpatient.setText("jLabel3");

        labeldoctor.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHREYAS\\OneDrive\\Desktop\\doctor.jpg")); // NOI18N
        labeldoctor.setText("jLabel3");

        buttondoctor.setText("doctor");
        buttondoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondoctorActionPerformed(evt);
            }
        });

        buttonpatient.setText("patient");
        buttonpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpatientActionPerformed(evt);
            }
        });

        buttonsystemadmin.setText("system admin");
        buttonsystemadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsystemadminActionPerformed(evt);
            }
        });

        buttonadmin.setText("community admin");
        buttonadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonadminActionPerformed(evt);
            }
        });

        buttoncancel.setText("cancel");
        buttoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncancelActionPerformed(evt);
            }
        });

        jButton1.setText("hospital admin ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(buttoncancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(buttondoctor)
                                .addGap(169, 169, 169)
                                .addComponent(buttonpatient)
                                .addGap(195, 195, 195)
                                .addComponent(buttonsystemadmin)
                                .addGap(198, 198, 198)
                                .addComponent(buttonadmin)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labeldoctor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(labelsystemadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(labeladmin, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120)
                        .addComponent(jButton1)))
                .addContainerGap(842, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labeldoctor, labelpatient});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttondoctor)
                            .addComponent(buttonpatient)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelsystemadmin)
                                .addComponent(labelpatient)
                                .addComponent(labeldoctor))
                            .addComponent(labeladmin))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonadmin)
                            .addComponent(buttonsystemadmin)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(buttoncancel)
                .addGap(19, 19, 19))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labeladmin, labeldoctor, labelpatient, labelsystemadmin});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonadminActionPerformed
        // TODO add your handling code here:
        communityentertoaccess ca = new communityentertoaccess();
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonadminActionPerformed

    private void buttondoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondoctorActionPerformed
        // TODO add your handling code here:
        doctorenteraccess dl = new doctorenteraccess();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttondoctorActionPerformed

    private void buttonpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpatientActionPerformed
        // TODO add your handling code here:
        patiententertoaccess pl = new patiententertoaccess();
        pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonpatientActionPerformed

    private void buttonsystemadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsystemadminActionPerformed
        // TODO add your handling code here:
        systemadminaccess sa = new systemadminaccess();
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonsystemadminActionPerformed

    private void buttoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncancelActionPerformed
        // TODO add your handling code here:
        this.hide();
        login lo = new login();
        lo.setVisible(true);
    }//GEN-LAST:event_buttoncancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hospitalentertoaccess ml = new hospitalentertoaccess();
        ml.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonadmin;
    private javax.swing.JButton buttoncancel;
    private javax.swing.JButton buttondoctor;
    private javax.swing.JButton buttonpatient;
    private javax.swing.JButton buttonsystemadmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labeladmin;
    private javax.swing.JLabel labeldoctor;
    private javax.swing.JLabel labelpatient;
    private javax.swing.JLabel labelsystemadmin;
    // End of variables declaration//GEN-END:variables
}
